# Generated by Django 5.1.1 on 2024-09-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compania',
            new_name='Campania',
        ),
        migrations.AlterModelTable(
            name='campania',
            table='campania',
        ),
    ]
